### ISSUE TITLE
blacklist: new admiral domain cannotwin.com

### ISSUE THREAD

**Issue by jordanmills** [paulgb/BarbBlock#36]
Is a DMCA takedown required for each domain, or just for bad actors who use it for any of their domains?

I'm not sure how to add a label.  Hopefully this works.

label:blacklist

**Comment by paulgb** [comment]
I don't require a DMCA takedown for Admiral domains (given that their MO is quickly churning a lot of domains), although there may be lists that have done a better job of curating Admiral specifically -- the motive of this repo was to create a deterrent from DMCA abuse rather than covering Admiral in depth.

In this case, the domain cannotwin.com seems to be unregistered?

**Comment by jordanmills** [comment]
After I posted this, I read down that rabbit hole.  I'm impressed at (and appreciate) the amount of work going into that.

Odd that it's not showing as registered.  It definitely came up as hosting a getadmiral script for me two days ago.  If it's gone, then that's another reason to disregard this issue.

Thanks for all the work.

**Comment by paulgb** [comment]
Weird, maybe they let it expire.
