### ISSUE TITLE
For curiosity Is this project still actively maintained

### ISSUE THREAD

**Issue by spirillen** [paulgb/BarbBlock#45]
For curiosity, Is this project still actively maintained, as last commit was Oct 16, 2023

**Comment by paulgb** [comment]
Hi @spirillen! Since BarbBlock narrowly-scoped to sites that inappropriately use DMCA takedowns to remove themselves from other blocklists, it doesn't need to be changed much. When it started up I feared that that would become more common, but happily it has not! That said, if it does happen again, I will be happy to add them.

**Comment by spirillen** [comment]
Super, I add you to my search project 👍🏻 https://github.com/external-sources/hosts-sources
